---
name: UrityAC
version: 1.0.0
main: OnlyJaiden\UrityAC\Main
api: [4.0.0, 5.0.0]
src-namespace-prefix: OnlyJaiden\UrityAC

commands:
  alerts:
    description: Stop getting annoying alerts.
    permission: UrityAC.alerts

permissions:
  UrityAC.alerts:
    default: op
    description: Get alerts from ac.
...
