---
name: ScrimAS
version: 0.5.0
main: OnlyJaiden\ScrimAS\Main
api: 4.2.4
src-namespace-prefix: OnlyJaiden\ScrimAS

commands:
  alerts:
    description: Stop getting annoying alerts.
    permission: alert.ac

permissions:
  alert.ac:
    default: op
    description: Get alerts from ac.
...
