# Please use § nothing else when doing the prefix
AntiCheat.prefix: "[§cAlerts§r]"
# Discord webhook support
webhook.enable: false
webhook.url: ""


# Cheats

# Movement
speed.enable: true
speed.max: 8.0

AutoClicker: true
MaxCPS: 1